version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: vislzr-db
    environment:
      POSTGRES_DB: vislzr
      POSTGRES_USER: vislzr
      POSTGRES_PASSWORD: vislzr_dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vislzr"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Backend
  api:
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    container_name: vislzr-api
    environment:
      DATABASE_URL: postgresql://vislzr:vislzr_dev_password@postgres:5432/vislzr
      GOOGLE_API_KEY: ${GOOGLE_API_KEY:-}
      CORS_ORIGINS: '["http://localhost:5173", "http://localhost:3000"]'
    ports:
      - "8000:8000"
    volumes:
      - ./packages/api:/app
      - /app/.venv  # Don't mount virtual env
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # React Frontend (Development)
  web:
    build:
      context: ./packages/web
      dockerfile: Dockerfile.dev
    container_name: vislzr-web
    environment:
      VITE_API_URL: http://localhost:8000
      VITE_WS_URL: ws://localhost:8000/ws
    ports:
      - "5173:5173"
    volumes:
      - ./packages/web:/app
      - /app/node_modules  # Don't mount node_modules
    depends_on:
      - api
    command: npm run dev -- --host 0.0.0.0

volumes:
  postgres_data:
    driver: local
